### ISSUE TITLE
Explore customizing sidebar

### ISSUE THREAD

**Issue by ccamara** [Librementor/librementor-book#1]
Is it possible to add an image (e.g. doi?). Apparently, is it possible to add custom HTML on sidebars in sphinx. In turn, Sphinx Book theme (which is used in jupyter book) allows those settings, as explained [here](https://sphinx-book-theme.readthedocs.io/en/latest/configure.html#control-the-left-sidebar-items). Also, jupyter-book allows adding custom sphinx config in its `config.yaml` file, as explained [here](https://jupyterbook.org/customize/config.html#advanced-configuration-with-sphinx).

However, the following code in `config.yaml` does not work:
```yaml
# Sphinx Configuration (see: )
sphinx:
  config:
    extra_navbar: "[![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.4322344.svg)](https://doi.org/10.5281/zenodo.4322344)"
```
